version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - jibit-mock
      - userproject
      - jenkins
    networks:
      - app-network

  jibit-mock:
    image: qasazgar/jibit-mock:v3
    container_name: jibit-mock
    expose:
      - "8000"
    networks:
      - app-network

  userproject:
    image: qasazgar/usersproject:v1
    container_name: userproject
    expose:
      - "80"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    expose:
      - "8080"
      - "50000"
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/var/jenkins_home/workspace
    networks:
      - app-network
  postman-tests:
    image: postman-tests:latest
    container_name: postman-tests
    build:
      context: /root/postman-tests
      dockerfile: Dockerfile
    networks:
      - app-network
volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge
